server:
  port: 8080

spring:
  application:
    name: temporal-demo
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Lily2702!!
    driverClassName: org.postgresql.Driver
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      platform: postgres